
sudo: true

language: java

install:
- ./dependencies.sh
- ls -ltrh /usr/share/fonts/    
- export path1=some-value
- wget https://github.com/bloomberg/scatteract/raw/master/fonts/BAUHS93.TTF
- ls -ltrh 
- sudo cp BAUHS93.TTF /usr/share/fonts/
- ls -ltrh /usr/local/share/fonts/
- ls -ltrh /usr/share/fonts/
- echo $path1
- fc-list | grep -i auhaus

script:
- Xvfb :5 -screen 0 800x600x24 &
- export DISPLAY=:5
- mvn clean verify
#- echo "in presteps DISPLAY is: $DISPLAY"

addons:
  # This configuration works to upload to AWS S3 buckets!    
  artifacts:
    s3_region: us-west-1
    paths:
    - openscad/models/src/main/openscad/name-tags/examples/light/light-cord-label-TOP-baseline.png
    - openscad/models/target/errorred-pngs.text
    - $(cat openscad/models/target/errorred-pngs.text | tr "\n" ":")
    target_paths: $TRAVIS_BUILD_NUMBER
#    working_dir: $WORKING_DIR
    bucket: openscad-2
    permissions: public-read
