
sudo: true

language: java

install:
- ./dependencies.sh

script:
- Xvfb :5 -screen 0 800x600x24 &
- export DISPLAY=:5
- mvn clean verify
#- echo "in presteps DISPLAY is: $DISPLAY"

addons:
  # This configuration works to upload to AWS S3 buckets!    
  artifacts:
    s3_region: us-west-1
    paths:
    - openscad/models/src/main/openscad/name-tags/examples/light/light-cord-label-TOP-baseline.png
    - target/errorred-pngs.text    
    target_paths: $TRAVIS_BUILD_NUMBER
#    working_dir: $WORKING_DIR
    bucket: openscad-2
    permissions: public-read
